from ..tiles.map_objects import Background
from ..maps.base import Map
from ..tiles.base import MapObject
from ..tiles.map_objects import Door, ExtDecor
from ..tiles.buildings import *
from ..coord import Coord

class Casino(Map):
    def __init__(self) -> None:
        super().__init__(
            name='Casino',
            size=(17, 17),
            entry_point=Coord(8, 5),
            description='description here',
            background_tile_image='black',
            background_music='blithe',
        )

    def get_objects(self) -> list[tuple[MapObject, Coord]]:
        objects = [
            (Background('casino_floor_red2'), Coord(x=5, y=6)),
            (Background('casino_floor_red2'), Coord(x=9, y=6)),
            (Background('casino_floor_red2'), Coord(x=10, y=6)),
            (Background('casino_floor_red2'), Coord(x=11, y=6)),
            (Background('casino_floor_red2'), Coord(x=8, y=6)),
            (Background('casino_floor_red2'), Coord(x=7, y=6)),
            (Background('casino_floor_red2'), Coord(x=6, y=6)),
            (Background('casino_floor_red'), Coord(x=3, y=5)),
            (Background('casino_floor_red'), Coord(x=5, y=5)),
            (Background('casino_floor_red'), Coord(x=7, y=5)),
            (Background('casino_floor_red'), Coord(x=1, y=5)),
            (Background('casino_floor_red'), Coord(x=2, y=5)),
            (Background('casino_floor_red'), Coord(x=4, y=5)),
            (Background('casino_floor_red'), Coord(x=6, y=5)),
            (Background('casino_floor_red'), Coord(x=8, y=5)),
            (Background('casino_floor_red'), Coord(x=9, y=5)),
            (Background('casino_floor_red'), Coord(x=10, y=5)),
            (Background('casino_floor_red'), Coord(x=11, y=5)),
            (Background('casino_floor_red'), Coord(x=12, y=5)),
            (Background('casino_floor_red'), Coord(x=13, y=5)),
            (Background('casino_floor_red'), Coord(x=14, y=5)),
            (Background('casino_floor_red'), Coord(x=15, y=5)),
            (Background('casino_floor_red'), Coord(x=16, y=5)),
            (Background('casino_floor_red2'), Coord(x=4, y=6)),
            (Background('casino_floor_red2'), Coord(x=3, y=6)),
            (Background('casino_floor_red2'), Coord(x=2, y=6)),
            (Background('casino_floor_red2'), Coord(x=1, y=6)),
            (Background('casino_floor_red2'), Coord(x=12, y=6)),
            (Background('casino_floor_red2'), Coord(x=13, y=6)),
            (Background('casino_floor_red2'), Coord(x=14, y=6)),
            (Background('casino_floor_red2'), Coord(x=16, y=6)),
            (Background('casino_floor_red2'), Coord(x=15, y=6)),
            (Background('casino_floor_red2'), Coord(x=1, y=4)),
            (Background('casino_floor_red2'), Coord(x=2, y=4)),
            (Background('casino_floor_red2'), Coord(x=3, y=4)),
            (Background('casino_floor_red2'), Coord(x=4, y=4)),
            (Background('casino_floor_red2'), Coord(x=5, y=4)),
            (Background('casino_floor_red2'), Coord(x=6, y=4)),
            (Background('casino_floor_red2'), Coord(x=7, y=4)),
            (Background('casino_floor_red2'), Coord(x=8, y=4)),
            (Background('casino_floor_red2'), Coord(x=9, y=4)),
            (Background('casino_floor_red2'), Coord(x=10, y=4)),
            (Background('casino_floor_red2'), Coord(x=11, y=4)),
            (Background('casino_floor_red2'), Coord(x=12, y=4)),
            (Background('casino_floor_red2'), Coord(x=13, y=4)),
            (Background('casino_floor_red2'), Coord(x=14, y=4)),
            (Background('casino_floor_red2'), Coord(x=15, y=4)),
            (Background('casino_floor_red2'), Coord(x=16, y=4)),
            (Background('casino_floor_red'), Coord(x=1, y=7)),
            (Background('casino_floor_red'), Coord(x=2, y=7)),
            (Background('casino_floor_red'), Coord(x=3, y=7)),
            (Background('casino_floor_red'), Coord(x=4, y=7)),
            (Background('casino_floor_red'), Coord(x=5, y=7)),
            (Background('casino_floor_red'), Coord(x=6, y=7)),
            (Background('casino_floor_red'), Coord(x=7, y=7)),
            (Background('casino_floor_red'), Coord(x=8, y=7)),
            (Background('casino_floor_red'), Coord(x=9, y=7)),
            (Background('casino_floor_red'), Coord(x=10, y=7)),
            (Background('casino_floor_red'), Coord(x=11, y=7)),
            (Background('casino_floor_red'), Coord(x=12, y=7)),
            (Background('casino_floor_red'), Coord(x=13, y=7)),
            (Background('casino_floor_red'), Coord(x=14, y=7)),
            (Background('casino_floor_red'), Coord(x=15, y=7)),
            (Background('casino_floor_red'), Coord(x=16, y=7)),
            (Background('casino_floor_red2'), Coord(x=0, y=6)),
            (Background('casino_floor_red2'), Coord(x=0, y=4)),
            (Background('casino_floor_red'), Coord(x=0, y=5)),
            (Background('casino_floor_red'), Coord(x=0, y=7)),
            (Background('casinoTile_12_11'), Coord(x=0, y=3)),
            (Background('casinoTile_12_11'), Coord(x=0, y=8)),
            (Background('casinoTile_12_13'), Coord(x=16, y=8)),
            (Background('casinoTile_12_13'), Coord(x=16, y=3)),
            (Background('casinoTile_12_13'), Coord(x=5, y=3)),
            (Background('casinoTile_12_13'), Coord(x=5, y=8)),
            (Background('casinoTile_12_11'), Coord(x=11, y=3)),
            (Background('casinoTile_12_11'), Coord(x=11, y=8)),
            (Background('casinoTile_12_12'), Coord(x=1, y=8)),
            (Background('casinoTile_12_12'), Coord(x=2, y=8)),
            (Background('casinoTile_12_12'), Coord(x=3, y=8)),
            (Background('casinoTile_12_12'), Coord(x=4, y=8)),
            (Background('casinoTile_12_12'), Coord(x=1, y=3)),
            (Background('casinoTile_12_12'), Coord(x=2, y=3)),
            (Background('casinoTile_12_12'), Coord(x=3, y=3)),
            (Background('casinoTile_12_12'), Coord(x=4, y=3)),
            (Background('casinoTile_12_12'), Coord(x=12, y=3)),
            (Background('casinoTile_12_12'), Coord(x=13, y=3)),
            (Background('casinoTile_12_12'), Coord(x=14, y=3)),
            (Background('casinoTile_12_12'), Coord(x=15, y=3)),
            (Background('casinoTile_12_12'), Coord(x=15, y=8)),
            (Background('casinoTile_12_12'), Coord(x=14, y=8)),
            (Background('casinoTile_12_12'), Coord(x=13, y=8)),
            (Background('casinoTile_12_12'), Coord(x=12, y=8)),
            (Background('casino_floor_blue'), Coord(x=6, y=8)),
            (Background('casino_floor_blue'), Coord(x=7, y=8)),
            (Background('casino_floor_blue'), Coord(x=8, y=8)),
            (Background('casino_floor_blue'), Coord(x=9, y=8)),
            (Background('casino_floor_blue'), Coord(x=10, y=8)),
            (Background('casino_floor_blue'), Coord(x=7, y=2)),
            (Background('casino_floor_blue'), Coord(x=9, y=2)),
            (Background('casino_floor_blue2'), Coord(x=7, y=9)),
            (Background('casino_floor_blue2'), Coord(x=9, y=9)),
            (Background('casino_floor_blue2'), Coord(x=6, y=3)),
            (Background('casino_floor_blue2'), Coord(x=7, y=3)),
            (Background('casino_floor_blue2'), Coord(x=8, y=3)),
            (Background('casino_floor_blue2'), Coord(x=9, y=3)),
            (Background('casino_floor_blue2'), Coord(x=10, y=3)),
            (make_group_house(1), Coord(x=6, y=9)),
            (make_group_house(52), Coord(x=6, y=2)),
            (make_group_house(13), Coord(x=10, y=2)),
            (make_group_house(63), Coord(x=10, y=9)),
            (Background('black'), Coord(x=12, y=10)),
            (Background('black'), Coord(x=13, y=10)),
            (Background('black'), Coord(x=12, y=9)),
            (Background('black'), Coord(x=16, y=9)),
            (Background('black'), Coord(x=13, y=9)),
            (Background('black'), Coord(x=14, y=9)),
            (Background('black'), Coord(x=15, y=9)),
            (Background('black'), Coord(x=14, y=10)),
            (Background('black'), Coord(x=15, y=10)),
            (Background('black'), Coord(x=16, y=10)),
            (Background('black'), Coord(x=0, y=10)),
            (Background('black'), Coord(x=1, y=10)),
            (Background('black'), Coord(x=2, y=10)),
            (Background('black'), Coord(x=3, y=10)),
            (Background('black'), Coord(x=0, y=9)),
            (Background('black'), Coord(x=1, y=9)),
            (Background('black'), Coord(x=2, y=9)),
            (Background('black'), Coord(x=3, y=9)),
            (Background('black'), Coord(x=4, y=9)),
            (Background('black'), Coord(x=4, y=10)),
            (Background('black'), Coord(x=0, y=11)),
            (Background('black'), Coord(x=1, y=11)),
            (Background('black'), Coord(x=2, y=11)),
            (Background('black'), Coord(x=3, y=11)),
            (Background('black'), Coord(x=4, y=11)),
            (Background('black'), Coord(x=5, y=11)),
            (Background('black'), Coord(x=11, y=11)),
            (Background('black'), Coord(x=12, y=11)),
            (Background('black'), Coord(x=13, y=11)),
            (Background('black'), Coord(x=14, y=11)),
            (Background('black'), Coord(x=15, y=11)),
            (Background('black'), Coord(x=16, y=11)),
            (Background('black'), Coord(x=0, y=2)),
            (Background('black'), Coord(x=0, y=1)),
            (Background('black'), Coord(x=1, y=1)),
            (Background('black'), Coord(x=1, y=0)),
            (Background('black'), Coord(x=0, y=0)),
            (Background('black'), Coord(x=1, y=2)),
            (Background('black'), Coord(x=2, y=2)),
            (Background('black'), Coord(x=3, y=2)),
            (Background('black'), Coord(x=4, y=2)),
            (Background('black'), Coord(x=2, y=1)),
            (Background('black'), Coord(x=3, y=1)),
            (Background('black'), Coord(x=2, y=0)),
            (Background('black'), Coord(x=3, y=0)),
            (Background('black'), Coord(x=4, y=0)),
            (Background('black'), Coord(x=5, y=0)),
            (Background('black'), Coord(x=4, y=1)),
            (Background('black'), Coord(x=11, y=0)),
            (Background('black'), Coord(x=12, y=0)),
            (Background('black'), Coord(x=13, y=0)),
            (Background('black'), Coord(x=13, y=1)),
            (Background('black'), Coord(x=14, y=1)),
            (Background('black'), Coord(x=15, y=1)),
            (Background('black'), Coord(x=14, y=0)),
            (Background('black'), Coord(x=15, y=0)),
            (Background('black'), Coord(x=16, y=0)),
            (Background('black'), Coord(x=12, y=1)),
            (Background('black'), Coord(x=12, y=2)),
            (Background('black'), Coord(x=13, y=2)),
            (Background('black'), Coord(x=14, y=2)),
            (Background('black'), Coord(x=15, y=2)),
            (Background('black'), Coord(x=16, y=2)),
            (Background('black'), Coord(x=16, y=1)),
            (make_group_house(25), Coord(x=8, y=9)),
            (make_group_house(34), Coord(x=8, y=2)),
            (Background('casino_floor_blue2'), Coord(x=5, y=9)),
            (Background('casino_floor_blue2'), Coord(x=11, y=9)),
            (Background('casino_floor_blue2'), Coord(x=5, y=1)),
            (Background('casino_floor_blue2'), Coord(x=6, y=1)),
            (Background('casino_floor_blue2'), Coord(x=7, y=1)),
            (Background('casino_floor_blue2'), Coord(x=9, y=1)),
            (Background('casino_floor_blue2'), Coord(x=8, y=1)),
            (Background('casino_floor_blue2'), Coord(x=10, y=1)),
            (Background('casino_floor_blue2'), Coord(x=11, y=1)),
            (Background('casino_floor_blue'), Coord(x=5, y=2)),
            (Background('casino_floor_blue'), Coord(x=11, y=2)),
            (Background('casino_floor_blue'), Coord(x=5, y=10)),
            (Background('casino_floor_blue'), Coord(x=6, y=10)),
            (Background('casino_floor_blue'), Coord(x=7, y=10)),
            (Background('casino_floor_blue'), Coord(x=8, y=10)),
            (Background('casino_floor_blue'), Coord(x=9, y=10)),
            (Background('casino_floor_blue'), Coord(x=10, y=10)),
            (Background('casino_floor_blue'), Coord(x=11, y=10)),
            (Background('casino_floor_blue'), Coord(x=6, y=0)),
            (Background('casino_floor_blue'), Coord(x=7, y=0)),
            (Background('casino_floor_blue'), Coord(x=8, y=0)),
            (Background('casino_floor_blue'), Coord(x=9, y=0)),
            (Background('casino_floor_blue'), Coord(x=10, y=0)),
            (Background('casino_floor_blue'), Coord(x=6, y=11)),
            (Background('casino_floor_blue'), Coord(x=7, y=11)),
            (Background('casino_floor_blue'), Coord(x=8, y=11)),
            (Background('casino_floor_blue'), Coord(x=9, y=11)),
            (Background('casino_floor_blue'), Coord(x=10, y=11)),
        ]

        door = Door('tube', linked_room="Trottier Town")
        objects.append((door, Coord(7, 0)))

        return objects
