
from ..coord import *
from .base import Map
from ..tiles.base import MapObject
from ..tiles.map_objects import *
from .map_helper import *
from ..tiles.buildings import *

class Forest(Map):
    def __init__(self) -> None:
        super().__init__(
            name='Forest',
            size=(50, 50),
            entry_point=Coord(8, 5),
            description='description here',
            background_tile_image='grass',
            background_music='blithe',
        )

    def get_objects(self) -> list[tuple[MapObject, Coord]]:
        objects = [
            (ExtDecor('tree_large_1'), Coord(x=3, y=5)),
            (make_group_house(97), Coord(x=3, y=0)),
            (make_group_house(41), Coord(x=11, y=11)),
            (make_group_house(46), Coord(x=26, y=3)),
            (make_group_house(29), Coord(x=4, y=26)),
            (make_group_house(39), Coord(x=35, y=18)),
            (make_group_house(12), Coord(x=19, y=27)),
            (make_group_house(3), Coord(x=40, y=31)),
            (ExtDecor('tree_large_1'), Coord(x=4, y=31)),
            (ExtDecor('tree_large_1'), Coord(x=19, y=32)),
            (ExtDecor('tree_large_1'), Coord(x=35, y=23)),
            (ExtDecor('tree_large_1'), Coord(x=40, y=36)),
            (ExtDecor('tree_large_1'), Coord(x=11, y=16)),
            (ExtDecor('tree_large_1'), Coord(x=26, y=8)),
            (ExtDecor('tree_large_1'), Coord(x=17, y=4)),
            (ExtDecor('tree_large_1'), Coord(x=5, y=13)),
            (ExtDecor('tree_large_1'), Coord(x=12, y=5)),
            (ExtDecor('tree_large_1'), Coord(x=23, y=13)),
            (ExtDecor('tree_large_1'), Coord(x=34, y=14)),
            (ExtDecor('tree_large_1'), Coord(x=39, y=5)),
            (ExtDecor('tree_large_1'), Coord(x=43, y=11)),
            (ExtDecor('tree_large_1'), Coord(x=47, y=24)),
            (ExtDecor('tree_large_1'), Coord(x=37, y=33)),
            (ExtDecor('tree_large_1'), Coord(x=31, y=31)),
            (ExtDecor('tree_large_1'), Coord(x=28, y=22)),
            (ExtDecor('tree_large_1'), Coord(x=33, y=28)),
            (ExtDecor('tree_large_1'), Coord(x=28, y=35)),
            (ExtDecor('tree_large_1'), Coord(x=45, y=42)),
            (ExtDecor('tree_large_1'), Coord(x=48, y=38)),
            (ExtDecor('tree_large_1'), Coord(x=40, y=46)),
            (ExtDecor('tree_large_1'), Coord(x=33, y=44)),
            (ExtDecor('tree_large_1'), Coord(x=36, y=41)),
            (ExtDecor('tree_large_1'), Coord(x=39, y=42)),
            (ExtDecor('tree_large_1'), Coord(x=30, y=41)),
            (ExtDecor('tree_large_1'), Coord(x=27, y=46)),
            (ExtDecor('tree_large_1'), Coord(x=24, y=40)),
            (ExtDecor('tree_large_1'), Coord(x=20, y=46)),
            (ExtDecor('tree_large_1'), Coord(x=15, y=44)),
            (ExtDecor('tree_large_1'), Coord(x=20, y=40)),
            (ExtDecor('tree_large_1'), Coord(x=14, y=39)),
            (ExtDecor('tree_large_1'), Coord(x=9, y=41)),
            (ExtDecor('tree_large_1'), Coord(x=5, y=44)),
            (ExtDecor('tree_large_1'), Coord(x=1, y=42)),
            (ExtDecor('tree_large_1'), Coord(x=3, y=38)),
            (ExtDecor('tree_large_1'), Coord(x=9, y=37)),
            (ExtDecor('tree_large_1'), Coord(x=11, y=35)),
            (ExtDecor('tree_large_1'), Coord(x=15, y=31)),
            (ExtDecor('tree_large_1'), Coord(x=15, y=23)),
            (ExtDecor('tree_large_1'), Coord(x=2, y=20)),
            (ExtDecor('tree_large_1'), Coord(x=6, y=16)),
            (ExtDecor('tree_large_1'), Coord(x=10, y=21)),
            (ExtDecor('tree_large_1'), Coord(x=16, y=20)),
            (ExtDecor('tree_large_1'), Coord(x=19, y=20)),
            (ExtDecor('tree_large_1'), Coord(x=23, y=23)),
            (ExtDecor('tree_large_1'), Coord(x=27, y=18)),
            (ExtDecor('tree_large_1'), Coord(x=31, y=17)),
            (ExtDecor('tree_large_1'), Coord(x=29, y=28)),
            (ExtDecor('tree_large_1'), Coord(x=21, y=8)),
            (ExtDecor('tree_large_1'), Coord(x=23, y=3)),
            (ExtDecor('tree_large_1'), Coord(x=30, y=14)),
            (ExtDecor('tree_large_1'), Coord(x=2, y=13)),
            (ExtDecor('tree_large_2'), Coord(x=1, y=10)),
            (ExtDecor('tree_large_2'), Coord(x=14, y=1)),
            (ExtDecor('tree_large_2'), Coord(x=27, y=12)),
            (ExtDecor('tree_large_2'), Coord(x=22, y=17)),
            (ExtDecor('tree_large_2'), Coord(x=35, y=2)),
            (ExtDecor('tree_large_2'), Coord(x=38, y=12)),
            (ExtDecor('tree_large_2'), Coord(x=35, y=7)),
            (ExtDecor('tree_large_2'), Coord(x=39, y=2)),
            (ExtDecor('tree_large_2'), Coord(x=36, y=4)),
            (ExtDecor('tree_large_2'), Coord(x=44, y=13)),
            (ExtDecor('tree_large_2'), Coord(x=43, y=5)),
            (ExtDecor('tree_large_2'), Coord(x=45, y=7)),
            (ExtDecor('tree_large_2'), Coord(x=47, y=18)),
            (ExtDecor('tree_large_2'), Coord(x=43, y=23)),
            (ExtDecor('tree_large_2'), Coord(x=44, y=24)),
            (ExtDecor('tree_large_2'), Coord(x=47, y=26)),
            (ExtDecor('tree_large_2'), Coord(x=32, y=34)),
            (ExtDecor('tree_large_2'), Coord(x=33, y=38)),
            (ExtDecor('tree_large_2'), Coord(x=44, y=45)),
            (ExtDecor('tree_large_2'), Coord(x=38, y=39)),
            (ExtDecor('tree_large_2'), Coord(x=17, y=41)),
            (ExtDecor('tree_large_2'), Coord(x=11, y=46)),
            (ExtDecor('tree_large_2'), Coord(x=6, y=38)),
            (ExtDecor('tree_large_2'), Coord(x=7, y=34)),
            (ExtDecor('tree_large_2'), Coord(x=21, y=41)),
            (ExtDecor('tree_large_2'), Coord(x=1, y=29)),
            (ExtDecor('tree_large_2'), Coord(x=1, y=34)),
            (ExtDecor('tree_large_2'), Coord(x=1, y=26)),
            (ExtDecor('tree_large_2'), Coord(x=3, y=22)),
            (ExtDecor('tree_large_2'), Coord(x=11, y=23)),
            (ExtDecor('tree_large_2'), Coord(x=15, y=24)),
            (ExtDecor('tree_large_2'), Coord(x=16, y=34)),
            (ExtDecor('tree_small_1'), Coord(x=0, y=10)),
            (ExtDecor('tree_small_1'), Coord(x=1, y=12)),
            (ExtDecor('tree_small_1'), Coord(x=3, y=15)),
            (ExtDecor('tree_small_1'), Coord(x=4, y=17)),
            (ExtDecor('tree_small_1'), Coord(x=3, y=16)),
            (ExtDecor('tree_small_1'), Coord(x=6, y=15)),
            (ExtDecor('tree_small_1'), Coord(x=4, y=18)),
            (ExtDecor('tree_small_1'), Coord(x=4, y=19)),
            (ExtDecor('tree_small_1'), Coord(x=5, y=20)),
            (ExtDecor('tree_small_1'), Coord(x=6, y=21)),
            (ExtDecor('tree_small_1'), Coord(x=7, y=23)),
            (ExtDecor('tree_small_1'), Coord(x=6, y=22)),
            (ExtDecor('tree_small_1'), Coord(x=9, y=8)),
            (ExtDecor('tree_small_1'), Coord(x=10, y=6)),
            (ExtDecor('tree_small_1'), Coord(x=11, y=6)),
            (ExtDecor('tree_small_1'), Coord(x=13, y=8)),
            (ExtDecor('tree_large_2'), Coord(x=10, y=8)),
            (ExtDecor('tree_large_2'), Coord(x=9, y=9)),
            (ExtDecor('tree_small_1'), Coord(x=10, y=23)),
            (ExtDecor('tree_small_1'), Coord(x=10, y=24)),
            (ExtDecor('tree_small_1'), Coord(x=10, y=25)),
            (ExtDecor('tree_small_1'), Coord(x=2, y=22)),
            (ExtDecor('tree_small_1'), Coord(x=2, y=23)),
            (ExtDecor('tree_small_1'), Coord(x=2, y=24)),
            (ExtDecor('tree_small_1'), Coord(x=2, y=31)),
            (ExtDecor('tree_small_1'), Coord(x=2, y=32)),
            (ExtDecor('tree_small_1'), Coord(x=2, y=36)),
            (ExtDecor('tree_small_1'), Coord(x=2, y=37)),
            (ExtDecor('tree_small_1'), Coord(x=5, y=39)),
            (ExtDecor('tree_small_1'), Coord(x=5, y=40)),
            (ExtDecor('tree_small_1'), Coord(x=8, y=38)),
            (ExtDecor('tree_small_1'), Coord(x=8, y=39)),
            (ExtDecor('tree_small_1'), Coord(x=11, y=37)),
            (ExtDecor('tree_small_1'), Coord(x=10, y=39)),
            (ExtDecor('tree_small_1'), Coord(x=11, y=38)),
            (ExtDecor('tree_small_1'), Coord(x=11, y=30)),
            (ExtDecor('tree_small_1'), Coord(x=11, y=31)),
            (ExtDecor('tree_small_1'), Coord(x=12, y=31)),
            (ExtDecor('tree_small_1'), Coord(x=12, y=32)),
            (ExtDecor('tree_small_1'), Coord(x=13, y=32)),
            (ExtDecor('tree_small_1'), Coord(x=14, y=32)),
            (ExtDecor('tree_small_1'), Coord(x=15, y=33)),
            (ExtDecor('tree_small_1'), Coord(x=13, y=37)),
            (ExtDecor('tree_small_1'), Coord(x=16, y=40)),
            (ExtDecor('tree_small_1'), Coord(x=19, y=41)),
            (ExtDecor('tree_small_1'), Coord(x=44, y=37)),
            (ExtDecor('tree_small_1'), Coord(x=44, y=38)),
            #(ExtDecor('tree_small_1'), Coord(x=44, y=39)),
            #(ExtDecor('tree_small_1'), Coord(x=43, y=41)),
            #(ExtDecor('tree_small_1'), Coord(x=42, y=42)),
            #(ExtDecor('tree_small_1'), Coord(x=41, y=43)),
            #(ExtDecor('tree_small_1'), Coord(x=38, y=42)),
            #(ExtDecor('tree_small_1'), Coord(x=35, y=41)),
            #(ExtDecor('tree_small_1'), Coord(x=32, y=40)),
            #(ExtDecor('tree_small_1'), Coord(x=32, y=41)),
            #(ExtDecor('tree_small_1'), Coord(x=23, y=42)),
            #(ExtDecor('tree_small_1'), Coord(x=26, y=42)),
            #(ExtDecor('tree_small_1'), Coord(x=27, y=42)),
            #(ExtDecor('tree_small_1'), Coord(x=28, y=43)),
            #(ExtDecor('tree_small_1'), Coord(x=29, y=43)),
            #(ExtDecor('tree_small_1'), Coord(x=30, y=44)),
            (ExtDecor('tree_small_1'), Coord(x=42, y=24)),
            (ExtDecor('tree_small_1'), Coord(x=42, y=25)),
            (ExtDecor('tree_small_1'), Coord(x=43, y=25)),
            (ExtDecor('tree_small_1'), Coord(x=44, y=26)),
            (ExtDecor('tree_small_1'), Coord(x=45, y=28)),
            (ExtDecor('tree_small_1'), Coord(x=45, y=26)),
            (ExtDecor('tree_small_1'), Coord(x=46, y=28)),
            (ExtDecor('tree_small_1'), Coord(x=47, y=29)),
            (ExtDecor('tree_small_1'), Coord(x=47, y=30)),
        ]

        door = Door('tube', linked_room="Trottier Town")
        objects.append((door, Coord(0, 0)))

        return objects

