
from ..coord import *
from .base import Map
from ..tiles.base import MapObject
from ..tiles.map_objects import *
from .map_helper import *
from ..tiles.buildings import *

class Rural(Map):
    def __init__(self) -> None:
        super().__init__(
            name='Generated Map',
            size=(25, 25),
            entry_point=Coord(8, 5),
            description='description here',
            background_tile_image='grass',
            background_music='blithe',
        )

    def get_objects(self) -> list[tuple[MapObject, Coord]]:
        objects  = [
            (make_group_house(15), Coord(x=16, y=2)),
            (make_group_house(17), Coord(x=11, y=16)),
            (Background('water_2'), Coord(x=10, y=0)),
            (Background('water_2'), Coord(x=10, y=1)),
            (Background('water_2'), Coord(x=11, y=2)),
            (Background('water_2'), Coord(x=11, y=0)),
            (Background('water_2'), Coord(x=11, y=1)),
            (Background('water_2'), Coord(x=11, y=3)),
            (Background('water_2'), Coord(x=12, y=6)),
            (Background('water_2'), Coord(x=12, y=7)),
            (Background('water_2'), Coord(x=12, y=8)),
            (Background('water_2'), Coord(x=13, y=9)),
            (Background('water_2'), Coord(x=13, y=10)),
            (Background('water_2'), Coord(x=14, y=11)),
            (Background('water_2'), Coord(x=15, y=11)),
            (Background('water_2'), Coord(x=15, y=12)),
            (Background('water_2'), Coord(x=16, y=12)),
            (Background('water_2'), Coord(x=17, y=12)),
            (Background('water_2'), Coord(x=17, y=13)),
            (Background('water_2'), Coord(x=19, y=13)),
            (Background('water_2'), Coord(x=20, y=13)),
            (Background('water_2'), Coord(x=20, y=14)),
            (Background('water_2'), Coord(x=20, y=15)),
            (Background('water_2'), Coord(x=20, y=16)),
            (Background('water_2'), Coord(x=20, y=17)),
            (Background('water_2'), Coord(x=21, y=17)),
            (Background('water_2'), Coord(x=21, y=18)),
            (Background('water_2'), Coord(x=22, y=18)),
            (Background('water_2'), Coord(x=22, y=19)),
            (Background('water_2'), Coord(x=23, y=19)),
            (Background('water_2'), Coord(x=23, y=20)),
            (Background('water_2'), Coord(x=23, y=21)),
            (Background('water_2'), Coord(x=23, y=22)),
            (Background('water_2'), Coord(x=23, y=23)),
            (Background('water_2'), Coord(x=24, y=23)),
            (Background('water_2'), Coord(x=24, y=24)),
            (Background('water_2'), Coord(x=18, y=13)),
            (Background('walkway'), Coord(x=18, y=13)),
            (ExtDecor('bridge', passable=True), Coord(x=11, y=4)),
            (Background('water_3'), Coord(x=11, y=4)),
            (Background('water_3'), Coord(x=11, y=5)),
            (Background('water_3'), Coord(x=12, y=4)),
            (Background('water_3'), Coord(x=12, y=5)),
            (Background('water_3'), Coord(x=13, y=4)),
            (Background('water_3'), Coord(x=13, y=5)),
            (Background('water_3'), Coord(x=11, y=6)),
            (Background('water_3'), Coord(x=11, y=7)),
            (Background('water_3'), Coord(x=12, y=3)),
            (Background('water_3'), Coord(x=12, y=2)),
            (Background('water_3'), Coord(x=10, y=2)),
            (Background('water_3'), Coord(x=10, y=3)),
            (Background('water_3'), Coord(x=13, y=3)),
            (Background('water_3'), Coord(x=13, y=2)),
            (Background('water_3'), Coord(x=12, y=1)),
            (Background('water_3'), Coord(x=12, y=0)),
            (Background('water_3'), Coord(x=13, y=6)),
            (Background('water_3'), Coord(x=13, y=7)),
            (Background('water_3'), Coord(x=13, y=8)),
            (Background('water_3'), Coord(x=14, y=8)),
            (Background('water_3'), Coord(x=14, y=9)),
            (Background('water_3'), Coord(x=14, y=10)),
            (Background('water_3'), Coord(x=15, y=10)),
            (Background('water_3'), Coord(x=16, y=10)),
            (Background('water_3'), Coord(x=16, y=11)),
            (Background('wood_diagonal'), Coord(x=14, y=5)),
            (Background('wood_diagonal'), Coord(x=14, y=6)),
            (Background('wood_diagonal'), Coord(x=15, y=7)),
            (Background('wood_diagonal'), Coord(x=15, y=9)),
            (Background('wood_diagonal'), Coord(x=17, y=9)),
            (Background('wood_diagonal'), Coord(x=18, y=9)),
            (Background('wood_diagonal'), Coord(x=19, y=9)),
            (Background('cobblestone'), Coord(x=14, y=4)),
            (Background('cobblestone'), Coord(x=14, y=7)),
            (Background('cobblestone'), Coord(x=15, y=8)),
            (Background('cobblestone'), Coord(x=16, y=9)),
            (Background('grass6'), Coord(x=10, y=4)),
            (Background('grass6'), Coord(x=10, y=5)),
            (Background('grass6'), Coord(x=9, y=5)),
            (Background('grass6'), Coord(x=9, y=4)),
            (Background('grass6'), Coord(x=8, y=4)),
            (Background('grass6'), Coord(x=8, y=5)),
            (Background('grass6'), Coord(x=7, y=5)),
            (Background('grass6'), Coord(x=7, y=4)),
            (Background('grass6'), Coord(x=6, y=4)),
            (Background('grass6'), Coord(x=6, y=5)),
            (Background('grass6'), Coord(x=5, y=4)),
            (Background('grass6'), Coord(x=5, y=5)),
            (Background('grass6'), Coord(x=4, y=5)),
            (Background('grass6'), Coord(x=4, y=6)),
            (Background('grass6'), Coord(x=3, y=6)),
            (Background('grass6'), Coord(x=3, y=7)),
            (Background('grass6'), Coord(x=2, y=7)),
            (Background('grass6'), Coord(x=2, y=8)),
            (Background('grass6'), Coord(x=2, y=9)),
            (Background('grass6'), Coord(x=2, y=10)),
            (Background('grass6'), Coord(x=2, y=11)),
            (Background('grass6'), Coord(x=2, y=12)),
            (Background('grass6'), Coord(x=2, y=13)),
            (Background('grass6'), Coord(x=2, y=14)),
            (Background('grass6'), Coord(x=2, y=15)),
            (Background('grass6'), Coord(x=3, y=15)),
            (Background('grass6'), Coord(x=3, y=16)),
            (Background('grass6'), Coord(x=3, y=17)),
            (Background('grass6'), Coord(x=4, y=17)),
            (Background('grass6'), Coord(x=3, y=5)),
            (Background('grass6'), Coord(x=2, y=5)),
            (Background('grass6'), Coord(x=2, y=4)),
            (Background('grass6'), Coord(x=2, y=3)),
            (Background('grass6'), Coord(x=1, y=3)),
            (Background('grass6'), Coord(x=1, y=2)),
            (Background('grass6'), Coord(x=1, y=1)),
            (Background('grass6'), Coord(x=0, y=0)),
            (Background('grass6'), Coord(x=0, y=1)),
            (Background('grass6'), Coord(x=0, y=2)),
            (Background('grass6'), Coord(x=4, y=18)),
            (Background('grass6'), Coord(x=5, y=18)),
            (Background('grass6'), Coord(x=5, y=20)),
            (Background('grass6'), Coord(x=6, y=20)),
            (Background('grass6'), Coord(x=6, y=21)),
            (Background('grass6'), Coord(x=6, y=22)),
            (Background('grass6'), Coord(x=7, y=22)),
            (Background('grass6'), Coord(x=7, y=23)),
            (Background('grass6'), Coord(x=8, y=23)),
            (Background('grass6'), Coord(x=9, y=23)),
            (Background('grass6'), Coord(x=10, y=23)),
            (Background('grass6'), Coord(x=11, y=23)),
            (Background('grass6'), Coord(x=13, y=23)),
            (Background('grass6'), Coord(x=12, y=23)),
            (Sign('sign'), Coord(x=14, y=23)),
            (Sign('sign'), Coord(x=20, y=9)),
            (make_group_house(37), Coord(x=6, y=9)),
            (Sign('sign'), Coord(x=9, y=16)),
            (Background('grass7'), Coord(x=18, y=12)),
            (Background('grass7'), Coord(x=18, y=11)),
            (Background('grass7'), Coord(x=19, y=11)),
            (Background('grass7'), Coord(x=20, y=11)),
            (Background('grass7'), Coord(x=19, y=10)),
            (Background('grass7'), Coord(x=21, y=11)),
            (Background('grass7'), Coord(x=22, y=11)),
            (Background('grass7'), Coord(x=22, y=12)),
            (Background('grass7'), Coord(x=22, y=13)),
            (Background('grass7'), Coord(x=23, y=13)),
            (Background('grass7'), Coord(x=23, y=14)),
            (Background('grass7'), Coord(x=24, y=14)),
            (Background('grass7'), Coord(x=18, y=14)),
            (Background('grass7'), Coord(x=18, y=15)),
            (Background('grass7'), Coord(x=18, y=16)),
            (Background('grass7'), Coord(x=18, y=17)),
            (Background('grass7'), Coord(x=18, y=18)),
            (Background('grass7'), Coord(x=18, y=19)),
            (Background('grass7'), Coord(x=18, y=20)),
            (Background('grass7'), Coord(x=18, y=21)),
            (Background('grass7'), Coord(x=18, y=22)),
            (Background('grass7'), Coord(x=17, y=22)),
            (Background('grass7'), Coord(x=17, y=23)),
            (Background('grass7'), Coord(x=16, y=23)),
            (Background('grass7'), Coord(x=16, y=24)),
            (Background('grass7'), Coord(x=15, y=24)),
            (Background('grass7'), Coord(x=14, y=24)),
            (Background('grass7'), Coord(x=13, y=24)),
            (Background('grass7'), Coord(x=5, y=19)),
            (Background('grass7'), Coord(x=4, y=19)),
            (Background('grass7'), Coord(x=3, y=19)),
            (Background('grass7'), Coord(x=3, y=20)),
            (Background('grass7'), Coord(x=3, y=21)),
            (Background('grass7'), Coord(x=2, y=21)),
            (Background('grass7'), Coord(x=2, y=22)),
            (Background('grass7'), Coord(x=1, y=22)),
            (Background('grass7'), Coord(x=1, y=23)),
            (Background('grass7'), Coord(x=0, y=23)),
            (Background('grass7'), Coord(x=0, y=24)),
            (Sign('sign'), Coord(x=1, y=24)),
            (Sign('sign'), Coord(x=24, y=13)),
            (ExtDecor('bush_spiky'), Coord(x=2, y=23)),
            (ExtDecor('bush_spiky'), Coord(x=0, y=21)),
            (make_group_house(10), Coord(x=0, y=24)),
            (make_group_house(140), Coord(x=24, y=14)),
            (ExtDecor('flower_cluster_red'), Coord(x=22, y=15)),
            (ExtDecor('flower_cluster_red'), Coord(x=23, y=16)),
            (ExtDecor('flower_large_yellow'), Coord(x=23, y=12)),
        ]

        door = Door('tube', linked_room="Trottier Town")
        objects.append((door, Coord(0, 0)))

        return objects