import random
from ..coord import *
from .base import Map
from ..tiles.base import MapObject
from ..tiles.map_objects import *
from .map_helper import *
from ..tiles.buildings import *

# [1,2]
# [8,2]
class UrbanCity(Map):
    def __init__(self) -> None:
        super().__init__(
            name="Urban City",
            size=(23, 35),
            entry_point=Coord(0, 2),
            description="An Urban City with two rows of upload houses",
            background_tile_image="",
            background_music="blue_val",
        )

    def get_objects(self) -> list[tuple[MapObject, Coord]]:
        objs=[
            (make_group_house(4), Coord(x=2, y=2)),
            (make_group_house(45), Coord(x=10, y=4)),
            (make_group_house(20), Coord(x=16, y=4)),
            (make_group_house(122), Coord(x=24, y=2)),
            (make_group_house(62), Coord(x=2, y=16)),
            (make_group_house(44), Coord(x=10, y=16)),
            (make_group_house(61), Coord(x=16, y=14)),
            (make_group_house(27), Coord(x=24, y=15)),
            *[(MapObject.get_obj('grass'), Coord(x, y)) for y in range(2,31) for x in range(1, 9)],
            *[(MapObject.get_obj('grass'), Coord(x, y)) for y in range(2,30) for x in range(16, 22)],
            
            *[(MapObject.get_obj('street1'), Coord(x=x, y=9)) for x in range(2, 32)],
            *[(MapObject.get_obj('road2'), Coord(x=x, y=9)) for x in range(32, 35)],
            *[(MapObject.get_obj('street1'), Coord(x=x, y=22)) for x in range(2, 31)],
            *[(MapObject.get_obj('street3'), Coord(x=x, y=0)) for x in [2, 4, 3, 1]],
            *[(MapObject.get_obj('street3'), Coord(x=1, y=y)) for y in range(1, 9)],
            (MapObject.get_obj('street2'), Coord(x=1, y=9)),
            *[(MapObject.get_obj(decor), Coord(x=x, y=y)) for decor, x, y in [
                ('road_decor6', 1, 8), ('road_decor8', 9, 8), ('road_decor8', 9, 20),
                ('road_decor8', 20, 8), ('road_decor8', 22, 20), ('road_decor6', 30, 8),
                ('road_decor4', 1, 15)
            ]],
            *[(MapObject.get_obj('street3'), Coord(x=1, y=y)) for y in range(15, 23)],
            *[(MapObject.get_obj('street3'), Coord(x=x, y=15)) for x in [
                2, 3, 4, 5, 7, 8, 9, 10, 12, 13, 15, 14, 11, 6, 23, 24, 25, 27, 26, 28, 29, 30]],
            *[(MapObject.get_obj('street3'), Coord(x=30, y=y)) for y in range(16, 23)],
            *[(MapObject.get_obj(street), Coord(x=30, y=22)) for street in ['street2', 'street1']],
           *[(MapObject.get_obj('road2'), Coord(x=0, y=y)) for y in 
            list(range(0, 4)) + [5, 6, 7, 8, 4] + list(range(9, 14)) + [15, 14, 16] + list(range(17, 23)) + [22, 21]],
            *[(MapObject.get_obj('street3'), Coord(x=31, y=y)) for y in range(8, -1, -1)],
            *[(MapObject.get_obj('street3'), Coord(x=x, y=0)) for x in 
            [30, 29, 27] + list(range(5, 9)) + [11, 14, 18, 22] + list(range(26, 29)) + [25, 24, 23, 21, 19, 20, 17, 16, 15, 13, 12, 10, 9]],
            
            (MapObject.get_obj('road2'), Coord(x=1, y=10)),
            (MapObject.get_obj('road8'), Coord(x=6, y=10)),
            (MapObject.get_obj('road8'), Coord(x=28, y=10)),
            (MapObject.get_obj('road1'), Coord(x=14, y=10)),
            (MapObject.get_obj('road2'), Coord(x=2, y=10)),
            (MapObject.get_obj('road2'), Coord(x=2, y=11)),
            (MapObject.get_obj('road2'), Coord(x=2, y=13)),
            (MapObject.get_obj('road2'), Coord(x=3, y=10)),
            (MapObject.get_obj('road2'), Coord(x=4, y=10)),
            (MapObject.get_obj('road2'), Coord(x=5, y=10)),
            (MapObject.get_obj('road2'), Coord(x=32, y=6)),
            (MapObject.get_obj('road2'), Coord(x=32, y=7)),
            (MapObject.get_obj('road2'), Coord(x=32, y=8)),
            (MapObject.get_obj('road2'), Coord(x=32, y=5)),
            (MapObject.get_obj('road2'), Coord(x=32, y=9)),
            (MapObject.get_obj('road2'), Coord(x=31, y=17)),
            (MapObject.get_obj('road2'), Coord(x=31, y=18)),
            (MapObject.get_obj('road2'), Coord(x=31, y=20)),
            (MapObject.get_obj('road2'), Coord(x=31, y=21)),
            (MapObject.get_obj('road2'), Coord(x=31, y=22)),
            (MapObject.get_obj('road2'), Coord(x=31, y=19)),
            (MapObject.get_obj('road9'), Coord(x=32, y=18)),
            (MapObject.get_obj('road9'), Coord(x=32, y=19)),
            (MapObject.get_obj('road9'), Coord(x=32, y=20)),
            (MapObject.get_obj('road9'), Coord(x=33, y=18)),
            (MapObject.get_obj('road9'), Coord(x=33, y=19)),
            (MapObject.get_obj('road9'), Coord(x=33, y=20)),
            (MapObject.get_obj('road9'), Coord(x=34, y=18)),
            (MapObject.get_obj('road9'), Coord(x=34, y=20)),
            (MapObject.get_obj('road9'), Coord(x=34, y=19)),
            (MapObject.get_obj('road9'), Coord(x=33, y=6)),
            (MapObject.get_obj('road9'), Coord(x=33, y=7)),
            (MapObject.get_obj('road9'), Coord(x=34, y=6)),
            (MapObject.get_obj('road9'), Coord(x=34, y=7)),
            (MapObject.get_obj('road6'), Coord(x=34, y=18)),
            (MapObject.get_obj('road6'), Coord(x=34, y=19)),
            (MapObject.get_obj('road6'), Coord(x=34, y=20)),
            (MapObject.get_obj('road7'), Coord(x=34, y=18)),
            (MapObject.get_obj('road7'), Coord(x=34, y=19)),
            (MapObject.get_obj('road7'), Coord(x=31, y=18)),
            (MapObject.get_obj('road7'), Coord(x=31, y=19)),
            (MapObject.get_obj('road7'), Coord(x=31, y=19)),
            (MapObject.get_obj('road7'), Coord(x=31, y=20)),
            (MapObject.get_obj('road2'), Coord(x=31, y=18)),
            (MapObject.get_obj('road2'), Coord(x=31, y=19)),
            (MapObject.get_obj('road2'), Coord(x=31, y=20)),
            (MapObject.get_obj('road2'), Coord(x=34, y=20)),
            (MapObject.get_obj('road9'), Coord(x=34, y=19)),
            (MapObject.get_obj('road9'), Coord(x=34, y=18)),
            (MapObject.get_obj('road9'), Coord(x=34, y=20)),
            (MapObject.get_obj('road2'), Coord(x=32, y=21)),
            (MapObject.get_obj('road2'), Coord(x=33, y=21)),
            (MapObject.get_obj('road2'), Coord(x=34, y=21)),
            (MapObject.get_obj('road2'), Coord(x=34, y=22)),
            (MapObject.get_obj('road2'), Coord(x=33, y=22)),
            (MapObject.get_obj('road2'), Coord(x=32, y=22)),
            (MapObject.get_obj('road2'), Coord(x=32, y=17)),
            (MapObject.get_obj('road2'), Coord(x=33, y=17)),
            (MapObject.get_obj('road2'), Coord(x=34, y=17)),
            (MapObject.get_obj('road2'), Coord(x=34, y=16)),
            (MapObject.get_obj('road2'), Coord(x=32, y=16)),
            (MapObject.get_obj('road2'), Coord(x=31, y=16)),
            (MapObject.get_obj('road2'), Coord(x=33, y=16)),
            (MapObject.get_obj('road2'), Coord(x=33, y=8)),
            (MapObject.get_obj('road2'), Coord(x=34, y=8)),
            (MapObject.get_obj('road2'), Coord(x=33, y=9)),
            (MapObject.get_obj('road2'), Coord(x=34, y=9)),
            (MapObject.get_obj('road2'), Coord(x=33, y=5)),
            (MapObject.get_obj('road2'), Coord(x=34, y=5)),
            (MapObject.get_obj('road2'), Coord(x=34, y=4)),
            (MapObject.get_obj('road2'), Coord(x=33, y=4)),
            (MapObject.get_obj('road2'), Coord(x=32, y=4)),
            (MapObject.get_obj('road2'), Coord(x=32, y=3)),
            (MapObject.get_obj('road2'), Coord(x=33, y=3)),
            (MapObject.get_obj('road2'), Coord(x=34, y=3)),
            (MapObject.get_obj('road2'), Coord(x=34, y=2)),
            (MapObject.get_obj('road2'), Coord(x=33, y=2)),
            (MapObject.get_obj('road2'), Coord(x=32, y=2)),
            (MapObject.get_obj('road2'), Coord(x=32, y=1)),
            (MapObject.get_obj('road2'), Coord(x=33, y=1)),
            (MapObject.get_obj('road2'), Coord(x=34, y=1)),
            (MapObject.get_obj('road2'), Coord(x=34, y=0)),
            (MapObject.get_obj('road2'), Coord(x=33, y=0)),
            (MapObject.get_obj('road2'), Coord(x=32, y=0)),
            (MapObject.get_obj('road7'), Coord(x=33, y=4)),
            (MapObject.get_obj('road7'), Coord(x=33, y=3)),
            (MapObject.get_obj('road7'), Coord(x=33, y=2)),
            (MapObject.get_obj('road7'), Coord(x=33, y=1)),
            (MapObject.get_obj('road7'), Coord(x=33, y=0)),
            (MapObject.get_obj('road3'), Coord(x=3, y=12)),
            (MapObject.get_obj('road3'), Coord(x=4, y=12)),
            (MapObject.get_obj('road3'), Coord(x=5, y=12)),
            (MapObject.get_obj('road3'), Coord(x=6, y=12)),
            (MapObject.get_obj('road3'), Coord(x=8, y=12)),
            (MapObject.get_obj('road3'), Coord(x=7, y=12)),
            (MapObject.get_obj('road3'), Coord(x=9, y=12)),
            (MapObject.get_obj('road3'), Coord(x=11, y=12)),
            (MapObject.get_obj('road3'), Coord(x=13, y=12)),
            (MapObject.get_obj('road3'), Coord(x=15, y=12)),
            (MapObject.get_obj('road3'), Coord(x=18, y=12)),
            (MapObject.get_obj('road3'), Coord(x=22, y=12)),
            (MapObject.get_obj('road3'), Coord(x=26, y=12)),
            (MapObject.get_obj('road3'), Coord(x=25, y=12)),
            (MapObject.get_obj('road3'), Coord(x=24, y=12)),
            (MapObject.get_obj('road3'), Coord(x=23, y=12)),
            (MapObject.get_obj('road3'), Coord(x=21, y=12)),
            (MapObject.get_obj('road3'), Coord(x=20, y=12)),
            (MapObject.get_obj('road3'), Coord(x=19, y=12)),
            (MapObject.get_obj('road3'), Coord(x=18, y=12)),
            (MapObject.get_obj('road3'), Coord(x=17, y=12)),
            (MapObject.get_obj('road3'), Coord(x=16, y=12)),
            (MapObject.get_obj('road3'), Coord(x=14, y=12)),
            (MapObject.get_obj('road3'), Coord(x=12, y=12)),
            (MapObject.get_obj('road3'), Coord(x=10, y=12)),

            
            (MapObject.get_obj('road3'), Coord(x=2, y=12)),
            (MapObject.get_obj('road3'), Coord(x=0, y=12)),
            (Door('tube', linked_room="Trottier Town"), Coord(x=0, y=12)),
            (MapObject.get_obj('road3'), Coord(x=1, y=12)),
            (MapObject.get_obj('road2'), Coord(x=1, y=11)),
            (MapObject.get_obj('road2'), Coord(x=2, y=11)),
            (MapObject.get_obj('road2'), Coord(x=3, y=11)),
            (MapObject.get_obj('road2'), Coord(x=4, y=11)),
            (MapObject.get_obj('road2'), Coord(x=1, y=13)),
            (MapObject.get_obj('road2'), Coord(x=2, y=13)),
            (MapObject.get_obj('road2'), Coord(x=3, y=13)),
            (MapObject.get_obj('road2'), Coord(x=1, y=14)),
            (MapObject.get_obj('road2'), Coord(x=2, y=14)),
            (MapObject.get_obj('road2'), Coord(x=3, y=14)),
            (MapObject.get_obj('road2'), Coord(x=4, y=14)),
            (MapObject.get_obj('road2'), Coord(x=4, y=13)),
            (MapObject.get_obj('road2'), Coord(x=5, y=13)),
            (MapObject.get_obj('road2'), Coord(x=5, y=14)),
            (MapObject.get_obj('road2'), Coord(x=6, y=13)),
            (MapObject.get_obj('road2'), Coord(x=7, y=14)),
            (MapObject.get_obj('road2'), Coord(x=8, y=13)),
            (MapObject.get_obj('road2'), Coord(x=5, y=11)),
            (MapObject.get_obj('road2'), Coord(x=6, y=11)),
            (MapObject.get_obj('road2'), Coord(x=7, y=10)),
            (MapObject.get_obj('road2'), Coord(x=7, y=11)),
            (MapObject.get_obj('road2'), Coord(x=8, y=10)),
            (MapObject.get_obj('road2'), Coord(x=8, y=11)),
            (MapObject.get_obj('road2'), Coord(x=9, y=10)),
            (MapObject.get_obj('road2'), Coord(x=9, y=11)),
            (MapObject.get_obj('road2'), Coord(x=10, y=10)),
            (MapObject.get_obj('road2'), Coord(x=11, y=11)),
            (MapObject.get_obj('road2'), Coord(x=11, y=11)),
            (MapObject.get_obj('road2'), Coord(x=11, y=10)),
            (MapObject.get_obj('road2'), Coord(x=13, y=10)),
            (MapObject.get_obj('road2'), Coord(x=12, y=10)),
            (MapObject.get_obj('road2'), Coord(x=12, y=11)),
            (MapObject.get_obj('road2'), Coord(x=13, y=11)),
            (MapObject.get_obj('road2'), Coord(x=14, y=11)),
            (MapObject.get_obj('road2'), Coord(x=15, y=11)),
            (MapObject.get_obj('road2'), Coord(x=15, y=10)),
            (MapObject.get_obj('road2'), Coord(x=16, y=10)),
            (MapObject.get_obj('road2'), Coord(x=16, y=11)),
            (MapObject.get_obj('road2'), Coord(x=10, y=11)),
            (MapObject.get_obj('road2'), Coord(x=9, y=13)),
            (MapObject.get_obj('road2'), Coord(x=7, y=13)),
            (MapObject.get_obj('road2'), Coord(x=6, y=14)),
            (MapObject.get_obj('road2'), Coord(x=8, y=14)),
            (MapObject.get_obj('road2'), Coord(x=9, y=14)),
            (MapObject.get_obj('road2'), Coord(x=10, y=13)),
            (MapObject.get_obj('road2'), Coord(x=10, y=14)),
            (MapObject.get_obj('road2'), Coord(x=11, y=13)),
            (MapObject.get_obj('road2'), Coord(x=11, y=14)),
            (MapObject.get_obj('road2'), Coord(x=12, y=13)),
            (MapObject.get_obj('road2'), Coord(x=13, y=14)),
            (MapObject.get_obj('road2'), Coord(x=13, y=13)),
            (MapObject.get_obj('road2'), Coord(x=12, y=14)),
            (MapObject.get_obj('road2'), Coord(x=14, y=13)),
            (MapObject.get_obj('road2'), Coord(x=14, y=14)),
            (MapObject.get_obj('road2'), Coord(x=15, y=14)),
            (MapObject.get_obj('road2'), Coord(x=15, y=13)),
            (MapObject.get_obj('road2'), Coord(x=16, y=13)),
            (MapObject.get_obj('road2'), Coord(x=17, y=13)),
            (MapObject.get_obj('road2'), Coord(x=19, y=13)),
            (MapObject.get_obj('road2'), Coord(x=21, y=13)),
            (MapObject.get_obj('road2'), Coord(x=20, y=13)),
            (MapObject.get_obj('road2'), Coord(x=18, y=13)),
            (MapObject.get_obj('road2'), Coord(x=17, y=11)),
            (MapObject.get_obj('road2'), Coord(x=17, y=10)),
            (MapObject.get_obj('road2'), Coord(x=18, y=10)),
            (MapObject.get_obj('road2'), Coord(x=18, y=11)),
            (MapObject.get_obj('road2'), Coord(x=19, y=10)),
            (MapObject.get_obj('road2'), Coord(x=19, y=11)),
            (MapObject.get_obj('road2'), Coord(x=20, y=10)),
            (MapObject.get_obj('road2'), Coord(x=20, y=11)),
            (MapObject.get_obj('road2'), Coord(x=21, y=10)),
            (MapObject.get_obj('road2'), Coord(x=21, y=11)),
            (MapObject.get_obj('road2'), Coord(x=22, y=10)),
            (MapObject.get_obj('road2'), Coord(x=22, y=11)),
            (MapObject.get_obj('road2'), Coord(x=22, y=13)),
            (MapObject.get_obj('road2'), Coord(x=23, y=13)),
            (MapObject.get_obj('road2'), Coord(x=25, y=13)),
            (MapObject.get_obj('road2'), Coord(x=23, y=11)),
            (MapObject.get_obj('road2'), Coord(x=24, y=12)),
            (MapObject.get_obj('road2'), Coord(x=24, y=13)),
            (MapObject.get_obj('road2'), Coord(x=23, y=14)),
            (MapObject.get_obj('road2'), Coord(x=24, y=14)),
            (MapObject.get_obj('road2'), Coord(x=25, y=14)),
            (MapObject.get_obj('road2'), Coord(x=27, y=14)),
            (MapObject.get_obj('road2'), Coord(x=26, y=13)),
            (MapObject.get_obj('road2'), Coord(x=26, y=14)),
            (MapObject.get_obj('road2'), Coord(x=27, y=13)),
            (MapObject.get_obj('road2'), Coord(x=27, y=12)),
            (MapObject.get_obj('road2'), Coord(x=24, y=11)),
            (MapObject.get_obj('road2'), Coord(x=25, y=11)),
            (MapObject.get_obj('road2'), Coord(x=26, y=11)),
            (MapObject.get_obj('road2'), Coord(x=27, y=11)),
            (MapObject.get_obj('road2'), Coord(x=27, y=10)),
            (MapObject.get_obj('road2'), Coord(x=26, y=10)),
            (MapObject.get_obj('road2'), Coord(x=24, y=10)),
            (MapObject.get_obj('road2'), Coord(x=23, y=10)),
            (MapObject.get_obj('road2'), Coord(x=25, y=10)),
            (MapObject.get_obj('road2'), Coord(x=28, y=11)),
            (MapObject.get_obj('road2'), Coord(x=28, y=12)),
            (MapObject.get_obj('road2'), Coord(x=28, y=13)),
            (MapObject.get_obj('road2'), Coord(x=28, y=14)),
            (MapObject.get_obj('road2'), Coord(x=29, y=14)),
            (MapObject.get_obj('road2'), Coord(x=29, y=13)),
            (MapObject.get_obj('road2'), Coord(x=31, y=13)),
            (MapObject.get_obj('road2'), Coord(x=30, y=14)),
            (MapObject.get_obj('road2'), Coord(x=31, y=14)),
            (MapObject.get_obj('road2'), Coord(x=31, y=15)),
            (MapObject.get_obj('road2'), Coord(x=32, y=15)),
            (MapObject.get_obj('road2'), Coord(x=34, y=15)),
            (MapObject.get_obj('road2'), Coord(x=34, y=14)),
            (MapObject.get_obj('road2'), Coord(x=33, y=14)),
            (MapObject.get_obj('road2'), Coord(x=32, y=14)),
            (MapObject.get_obj('road2'), Coord(x=32, y=13)),
            (MapObject.get_obj('road2'), Coord(x=33, y=13)),
            (MapObject.get_obj('road2'), Coord(x=34, y=13)),
            (MapObject.get_obj('road2'), Coord(x=34, y=12)),
            (MapObject.get_obj('road2'), Coord(x=34, y=10)),
            (MapObject.get_obj('road2'), Coord(x=33, y=10)),
            (MapObject.get_obj('road2'), Coord(x=30, y=10)),
            (MapObject.get_obj('road2'), Coord(x=29, y=10)),
            (MapObject.get_obj('road2'), Coord(x=29, y=11)),
            (MapObject.get_obj('road2'), Coord(x=29, y=12)),
            (MapObject.get_obj('road2'), Coord(x=30, y=11)),
            (MapObject.get_obj('road2'), Coord(x=30, y=12)),
            (MapObject.get_obj('road2'), Coord(x=30, y=13)),
            (MapObject.get_obj('road2'), Coord(x=31, y=12)),
            (MapObject.get_obj('road2'), Coord(x=31, y=11)),
            (MapObject.get_obj('road2'), Coord(x=31, y=10)),
            (MapObject.get_obj('road2'), Coord(x=32, y=10)),
            (MapObject.get_obj('road2'), Coord(x=32, y=11)),
            (MapObject.get_obj('road2'), Coord(x=32, y=12)),
            (MapObject.get_obj('road2'), Coord(x=33, y=11)),
            (MapObject.get_obj('road2'), Coord(x=33, y=12)),
            (MapObject.get_obj('road2'), Coord(x=33, y=15)),
            (MapObject.get_obj('road2'), Coord(x=34, y=11)),
            (MapObject.get_obj('street5'), Coord(x=4, y=15)),
            (MapObject.get_obj('street5'), Coord(x=8, y=15)),
            (MapObject.get_obj('street5'), Coord(x=11, y=15)),
            (MapObject.get_obj('street5'), Coord(x=14, y=15)),
            (MapObject.get_obj('street5'), Coord(x=12, y=15)),
            (MapObject.get_obj('street5'), Coord(x=27, y=15)),
            (MapObject.get_obj('street5'), Coord(x=29, y=15)),
            (MapObject.get_obj('street5'), Coord(x=3, y=0)),
            (MapObject.get_obj('street5'), Coord(x=8, y=0)),
            (MapObject.get_obj('street5'), Coord(x=16, y=0)),
            (MapObject.get_obj('street5'), Coord(x=21, y=0)),
            (MapObject.get_obj('street5'), Coord(x=27, y=0)),
            (MapObject.get_obj('road_decor2'), Coord(x=33, y=11)),
            (MapObject.get_obj('road_decor2'), Coord(x=33, y=12)),
            (MapObject.get_obj('road_decor2'), Coord(x=33, y=13)),
            (Sign('sign',text="Claim your house..."), Coord(x=8, y=9)),
            (Sign('sign',text="Claim your house..."), Coord(x=14, y=9)),
            (Sign('sign',text="Claim your house..."), Coord(x=22, y=9)),
            (Sign('sign',text="Claim your house..."), Coord(x=26, y=9)),
            (Sign('sign',text="Claim your house..."), Coord(x=6, y=21)),
            (Sign('sign',text="Claim your house..."), Coord(x=12, y=21)),
            (Sign('sign',text="Claim your house..."), Coord(x=18, y=21)),
            (Sign('sign',text="Claim your house..."), Coord(x=27, y=21)),
        ]

        return objs
